AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  PyWeather-Demo : Creates the PyWeatherDemo Lambda - a simple Python3.11 Lambda function that helps showcase the basic features of Lambda, but uses a more sophisticated rollout.

Parameters:
  SecretArn:
    Type: String
    Default: "arn:aws:secretmanager:REGION:ACCOUNTID:secret:SECRETNAME"
    Description: "Enter the ARN of the Secrets Manager Secret that holds the OpenWeatherMap API Key (You must create this yourself!)"

Resources:

  PyWeatherDemo:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64 
        #- arm64
      Timeout: 30
      # X-Ray tracing enabled. Perms will be added automatically by SAM
      Tracing: Active
      # The AutoPublishAlias term tells the framework to detect when the function changes, and then deploy it using the live alias. 
      AutoPublishAlias: live
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:        # Policy template with placeholder value
            SecretArn: !Ref SecretArn
      DeploymentPreference:
        # A CodeDeploy Application and DeploymentGroup will be created for this Lambda
        #The deployment configuration determines the rate at which your CodeDeploy application shifts traffic from the original version of the Lambda function to the new version. 
        # NOTE: This is a custom DeploymentConfig to do a 80/20 Canary for 5 minutes (good for demos!)
        # This is defined in pipeline/pipeline.yaml
        Type: EightyTwentyCanary
        # Another "stock" option - this takes a long time.
        # Type: CodeDeployDefault.LambdaCanary10Percent5Minutes
        # OR (This one is similar to DSS class) 
        #Type: Linear10PercentEvery1Minute
        
        # Specifies Lambda functions for deployment lifecycle hooks
        Hooks:
          # Test the new version before we start allowing invocations. If this fails, we rollback.
          PreTraffic: !Ref beforeAllowTraffic
          # Test the new verstion after we start allowing invocations. This runs ONCE at the END of the 5 minute canary period. If this fails we roll back.
          PostTraffic: !Ref afterAllowTraffic
      Events:
        PyWeatherDemoGet:
          #
          # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html
          #
          Type: Api 
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /weather
            Method: get

  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PyWeather-Demo-API
      StageName: dev
      Path: /weather
      Method: get
      #
      # Tracing is on for this REST API
      # Did you know you can see the COLD START and WARM START delay in X-Ray traces?
      #
      TracingEnabled: true
      # Did you know API GW REST API has a 29 second HARD LIMIT on timeout?
      # (HTTP API has a 30 second HARD LIMIT on timeout)
      TimeoutInMillis: 29000

  # NOTE: When you use "Events" above SAM will create an Implicit AWS::Lambda::Permission
  # (Check stack resources - you can see it there)
  # BUT - it DOES NOT show up in the console or command line.
  # This manual entry theoretically makes the same settings, but isn't properly recognized by the console (so there will be an error showing - but it is meaningless.)
  # However - it does ensure that the Trigger button is highlighted in the console, 
  # So that is a good reminder that an API GW is set to trigger this lambda.
  # I *think* it's because of the alias
  APIGWPermission:
    Type: AWS::Lambda::Permission
    Properties:
      # This can be name/arn/partial arn
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-functionname
      FunctionName: !Sub '${PyWeatherDemo}'
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      # NOTE: ServerlessRestApi is an implicit Logical ID created by SAM. You won't find it in this template.
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*/GET/weather'
      # None of these work any better... 2023-10-30
      #SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*/*/${PyWeatherDemo}'
      #SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*/GET/weather/${PyWeatherDemo}'
      
  # Specifies the BeforeAllowTraffic lifecycle hook Lambda function
  beforeAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src-BeforeAllowTraffic/
      Handler: beforeAllowTraffic.handler
      Policies:
        - Version: "2012-10-17"
          # Grants this function permission to call codedeploy:PutLifecycleEventHookExecutionStatus        
          Statement: 
          - Effect: "Allow"
            Action: 
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: "2012-10-17"
          # Grants this function permission to call lambda:InvokeFunction        
          Statement: 
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: !Ref PyWeatherDemo.Version
      Runtime: nodejs18.x
      # Specifies the name of the Lambda hook function      
      FunctionName: 'CodeDeployHook_beforeAllowTraffic_PyWeatherDemo'
      DeploymentPreference:
        Enabled: false
      Timeout: 10
      Environment:
        Variables:
          NewVersion: !Ref PyWeatherDemo.Version
          
  # Specifies the AfterAllowTraffic lifecycle hook Lambda function
  afterAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src-AfterAllowTraffic/
      Handler: afterAllowTraffic.handler
      Policies:
        - Version: "2012-10-17"
          Statement: 
          # Grants this function permission to call codedeploy:PutLifecycleEventHookExecutionStatus         
          - Effect: "Allow"
            Action: 
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: "2012-10-17"
          Statement: 
          # Grants this function permission to call lambda:InvokeFunction          
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: !Ref PyWeatherDemo.Version
      Runtime: nodejs18.x
      # Specifies the name of the Lambda hook function      
      FunctionName: 'CodeDeployHook_afterAllowTraffic_PyWeatherDemo'
      DeploymentPreference:
        Enabled: false
      Timeout: 10
      Environment:
        Variables:
          NewVersion: !Ref PyWeatherDemo.Version

  # This is a simplified version of the PyWeather function 
  # used specficially for a Step Functions State Machine demo.
  PyWeatherJSON:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src-PyWeatherJSON/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:        # Policy template with placeholder value
            SecretArn: !Ref SecretArn

Outputs:
  # API Gateway endpoint as an output, for convenience
  PyWeatherDemoRESTApiURL:
    Description: "API Gateway endpoint URL for Prod stage - change the city as desired."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/weather?city=Scranton"
    Export:
      Name: PyWeatherDemoRestApiUrl

  PyWeatherDemoRestApi:
    Description: "The first portion for a fixup script to use"
    Value: !Sub "${ServerlessRestApi}"
    Export:
      Name: PyWeatherDemoRestApi  

  PyWeatherDemoAccount:
    Description: "The account id the lambda is installed into"
    Value: !Ref AWS::AccountId
    Export:
      Name: PyWeatherDemoAccountId

  PyWweatherLambdaName:
    Description: "The physical name of the lambda that was created"
    Value: !Ref PyWeatherDemo
    Export:
      Name: PyWeatherDemoLambdaName