AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  PyWeather-Demo : PyWeatherDemo Lambda - a simple Python3.11 Lambda function that helps showcase the basic features of Lambda.

Parameters:
  SecretArn:
    Type: String
    Default: "arn:aws:secretmanager:REGION:ACCOUNTID:secret:SECRETNAME"
    Description: "Enter the ARN of the Secrets Manager Secret that holds the OpenWeatherMap API Key (You must create this yourself!)"

Globals:
  Function:
    Timeout: 30

Resources:
  PyWeatherDemo:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64 
        #- arm64 
      Timeout: 30
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:        # Policy template with placeholder value
            SecretArn: !Ref SecretArn
      Events:
        PyWeatherDemo:
          # Turn it into a REST API via API Gateway
          # API Gateway - but there's TONS more options to trigger this Lambda.
          # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventsource.html
          Type: Api 
          Properties:
            Path: /weather
            Method: get
            # Did you know API GW has a 29 second HARD LIMIT on timeout?
            # You do now.... 
            TimeoutInMillis: 29000
            
Outputs:
  # API Gateway endpoint as an output, for convenience
  PyWeatherDemoRESTApi:
    Description: "API Gateway endpoint URL for Prod stage - change the city as desired."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/weather?city=Scranton"

  PyWeatherDemo:
    Description: "Function ARN."
    Value: !GetAtt PyWeatherDemo.Arn
